### ISSUE TITLE
Native Compiling on Linux

### ISSUE THREAD

**Issue by pietrotedeschi** [fkie-cad/bpmac#1]
- I am compiling the code on Ubuntu 22.04 by using the last version of contiki-ng.
- I am using the following flags: ```CFLAGS += -DWITH_DTLS=1 -DMAC_LEN=16 -DIS_ZOUL=1 -DUSE_HW_ACCEL=0```
- When I run ```make TARGET=native client``` it seems  that the sha256 library is not found
```
Building with tinyDTLS - see ../os/net/security/tinydtls/LICENSE
  CC        client.c
In file included from ../os/net/security/tinydtls/tinydtls.h:35,
                 from client.c:31:
../bpmac/tinydtls-support/dtls-support-conf.h:75:10: fatal error: dev/sha256.h: No such file or directory
   75 | #include "dev/sha256.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [../Makefile.include:498: build/native/obj/client.o] Error 1
```
Any suggestion?

**Comment by eric-wagner** [comment]
The problem seem to be that the USE_HW_ACCEL cannot be used for the native compilaton. I.e. there is a difference between -DUSE_HW_ACCEL=0 and removing the flag entirely. 

`CFLAGS += -DWITH_DTLS=1 -DMAC_LEN=16 -DIS_ZOUL=1` should do the job.

**Comment by pietrotedeschi** [comment]
> The problem seem to be that the USE_HW_ACCEL cannot be used for the native compilaton. I.e. there is a difference between -DUSE_HW_ACCEL=0 and removing the flag entirely.
> 
> `CFLAGS += -DWITH_DTLS=1 -DMAC_LEN=16 -DIS_ZOUL=1` should do the job.

Thank you @eric-wagner. However, I am using gcc version 11.2.0 and I also received other errors during the building process such as:
- bpmac.c:191:9: error: ‘rijndaelEncrypt’ reading 16 bytes from a region of size 8 (I temporary fixed by adding ``-Wno-stringop-overread`` in CFLAGS)
- umac.c:1704:30: error: argument 1 of type ‘char[]’ with mismatched bound (I temporary fixed with ``uhash_ctx_t uhash_alloc(char key[16])`` in umac.c)
- However, after that, I try to compile again and I receive the error: ``in function `bpmac_sign': bpmac.c:(.text+0x41a): undefined reference to `xor_tags'``. So, I moved (and removed ``inline``) ``void xor_tags(void* tag, void* value) __attribute__ ((optimize(3)));`` from bpmac.c to bpmac.h.
- Now it compiles, but please, if you can propose better and more efficient fixes, they are welcome!

**Comment by eric-wagner** [comment]
I finally had time to investigate this issue further. The problem seem to stem from the compiler version, as using gcc version 11.1.0 causes issues for me as well. However, the first two errors occur in code that is not by myself, which I want to adjust as little as possible to not cause issues with any benchmarking.

Moving the declaration of xor_tags seems like a good idea and also does not break the compilation for any other tested devices. I pushed this change and also made the Makefile directly compatible with native compilation.

Furthermore, I put a note in the README that gcc version 9.4 seems to work best.
